name: data101

channels:
  - conda-forge

dependencies:
  # Postgresql client DH-363
  - postgresql==17.5
  - beautifulsoup4==4.13.4
  - black==25.1.0
  - bokeh==3.7.3
  - coverage==7.10.1
  - cython==3.1.2
  - dbt-postgres==1.9.0
  - folium==0.20.0
  - h5netcdf==1.6.3
  - ipyparallel==9.0.1
  - ipython-sql==0.3.9
  - jsonschema==4.24.0
  - jupysql==0.11.1
  - jupyterlab-geojson==3.4.0
  - jupyterlab-variableinspector==3.2.4
  - mongo-tools==100.12.2
  - nbdime==4.0.2
  - numba==0.61.2
  - pandoc==2.12
  - pandocfilters==1.5.0
  - pep8==1.7.1
  - pgspecial==2.2.1
  - prettytable==3.16.0
  - psycopg==3.2.9
  - pyarrow==20.0.0
  - pymongo==4.13.2
  - pytables==3.10.2
  - pytest==8.4.1
  - pytest-cov==6.2.1
  - pytest-notebook==0.10.0
  - python-pdfkit==1.0.0
  - requests==2.32.4
  - sqlalchemy==2.0.41
  - sqlparse==0.5.3
  - tqdm==4.67.1
  - xlrd==2.0.1
  # DH-663, requested by Silas
  - dill==0.4.1
  - ipython==9.13.0
  - pytz==2026.2

  - pip:
      # items required for basic functionality
      # other stuff
      - iwut==0.0.4
      # [DH-418] cannot get mamba to install this
  #    - tensorflow-cpu==2.18.0
      # [DH-418] cannot get mamba to install this
  #    - geopandas==0.12.1
      # disable until fixed (probably this:  https://github.com/jupyterlab/jupyter-collaboration/issues/162)
      # DH-418, 2024-01-16, above issue still not fixed.  Also this package is available in condaforge
      # https://anaconda.org/conda-forge/jupyter-collaboration
      # - jupyter_collaboration==1.0.1
      # - git+https://github.com/shaneknapp/python-popularity-contest.git@add-error-handling
      - jupyterlab-a11y-checker==0.1.3 # Adding a11y-checker for Data 101 staff's exploration
